### ISSUE TITLE
ESPAsyncWebServer.h library version

### ISSUE THREAD

**Issue by dabu667** [dasdgw/yoradio#15]
Hi,
First of all, I think it's nice that somebody is still improving this project.
I'm trying to compile it under Arduino IDE and I have a question: is this meant to work only with this version of Async Web Server: [https://github.com/me-no-dev/ESPAsyncWebServer](https://github.com/me-no-dev/ESPAsyncWebServer)? It seems the only one to compile.
I am asking because, after I manually install the above library Arduino IDE says there's an update and wants to replace it with [https://github.com/mathieucarbou/ESPAsyncWebServer](https://github.com/mathieucarbou/ESPAsyncWebServer) which doesn't compile.

**Comment by dasdgw** [comment]
Hi,
sorry to hear that you have compiling issues.
We only test against the me-no-dev version. This seems to be the original repo of ESPAsyncWebServer, while the version from mathieucarbou is a fork of a fork from me-no-dev.
(https://github.com/me-no-dev/ESPAsyncWebServer -> https://github.com/yubox-node-org/ESPAsyncWebServer -> https://github.com/mathieucarbou/ESPAsyncWebServer)
I don't know why the arduino ide wants to update to the mentioned version. Last time I used the arduino ide feals like a decade ago. So I'm of no help on that.
One of the improvements was moving this project to platformio. :-) Some of the new features are only available by using the platformio.ini.  Updating the readme is on my todo list.

Your links are pointing to the wrong urls. Just add them as text. If you are using the chain symbol you have to replace 'url' with the url you want to link to.

**Comment by dabu667** [comment]
Hi,

Thanks for clarifying that this project is intended to use the me-no-dev lib version.
For me, the important thing was to see if the new version of audio I2S library would fix the dropouts on some streams that I experience right now. I also thought that a newer version of the ESPAsyncWebServer would help.
I'll try to switch to Platformio for this project. I also edited the links in my previous post.
