### ISSUE TITLE
Can this still be uploaded using Arduino IDE?

### ISSUE THREAD

**Issue by CoolmdXi** [dasdgw/yoradio#18]
if the project can be uploaded still using Arduino IDE, any chance of quick how too. I have the JC4827W543 C board and would so love to get it to run the yoradio as I have made a few others and love the radio

**Comment by dabu667** [comment]
I have a similar board: 2.8 inch ESP32-2432S028R to which I soldered  a PSRAM IC. The only lucky combo in which it works is:
 - ESP32 core 2.0.14 based on IDF 4.4.6; after this the IDF changes, also the I2S driver changes after 3.0
 - audio lib 3.0.11c from schreibfaul1 - used by the main branch of this project, not the latest 3.0.12h
 Any other combination that I tried resulted in stuttering of the audio and display and sometimes reboots. I could not figure out how to use the latest audio library.

For the rest of the libs to be safe I used the versions from this project:
-   adafruit/Adafruit BusIO@^1.14.5
-   adafruit/Adafruit GFX Library@^1.11.9  --- de inlocuit fontul
-   bblanchon/ArduinoJson@^7.0.4
-   https://github.com/me-no-dev/ESPAsyncWebServer 
-   adafruit/Adafruit ILI9341

Hope this helps.

**Comment by CoolmdXi** [comment]
Hi dabu, Yes I had previously got the original yoradio to work with the CYD board you mention. I used the original method and didnt have any problems.
 But I have not recently tried to compile it since some of the updates you talk about. The JC..543 display is requires a completley different type of display driver to the normal 2.8" CYD boards and only a few display libraries support it, bb_spi_lcd, Arduino_gfx etc. Not supported by Tft_espi etc, which is a shame

**Comment by dabu667** [comment]
Oh, I understand .. different board and display driver. Sorry, can't help.

**Comment by CoolmdXi** [comment]
Finally managed to get this to upload to JC4827W543 cap touch, but i have no Touch, not sure exactly what to add in the myoptions.h. i know the touch pins but not sure what exact syntax needs to be used? could you please help?
